name: release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: v1.0.0
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use: addnab/docker-run-action@v3
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        uses: addnab/docker-run-action@v3
        with:
          image: frolvlad/alpine-gcc:latest
          options: -v ${{ github.workspace }}:/ss
          shell: sh
          run: |
            ls
            echo ${{ github.workspace }}
            cd /ss
            sh ic.sh
            cp build/src/ss_local ss-local-${{ matrix.job.target }}-${{ github.event.inputs.version }}
      - name: new tag
        run: git tag ${{ github.event.inputs.version }}
        run: git push origin ${{ github.event.inputs.version }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'ss-local*'
            draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}